se-edu/addressbook-level4

data/addressbook.xml, src/main/java/seedu/address/commands/DeletePersonCommand.java, src/main/java/seedu/address/commands/TargetLastListedPersonCommand.java, src/main/java/seedu/address/controller/MainWindow.java, src/main/java/seedu/address/controller/PersonCardController.java, src/main/java/seedu/address/controller/PersonListPanel.java, src/main/java/seedu/address/controller/Ui.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/parser/Parser.java, src/main/java/seedu/address/ui/PersonListViewCell.java
=> Implement DeleteCommand #15

src/test/java/guitests/PersonDeleteCommandTest.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java
=> Delete command GUI tests #31

src/main/java/seedu/address/commands/HelpCommand.java, src/main/java/seedu/address/controller/MainWindow.java, src/main/java/seedu/address/controller/Ui.java, src/main/java/seedu/address/events/ui/ShowHelpEvent.java
=> support Help command #22

src/main/resources/view/MainWindow.fxml
=> Increase height of StatusBarHeader #25

src/main/java/seedu/address/controller/CommandBox.java, src/test/java/guitests/ClearCommandBoxTest.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java
=> clear command box after executing command #37

.gitignore, src/main/java/seedu/address/controller/CommandBox.java, src/main/java/seedu/address/controller/MainWindow.java, src/main/java/seedu/address/controller/ResultDisplay.java, src/main/java/seedu/address/controller/StatusBarHeader.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml, src/main/resources/view/StatusBarHeader.fxml, src/test/java/guitests/guihandles/HeaderStatusBarHandle.java
=> Tweak GUI to emphasize active components #48

build.gradle
=> Gradle is not running unit tests #62

src/main/java/seedu/address/commands/Command.java, src/main/java/seedu/address/commands/FindPersonsByWordsInNameCommand.java, src/main/java/seedu/address/commons/StringUtil.java, src/test/java/guitests/PersonSearchCommandTest.java
=> Search substring will return incorrect feedback message #41

src/main/java/seedu/address/commands/SelectPersonCommand.java, src/main/java/seedu/address/controller/PersonListPanel.java, src/main/java/seedu/address/controller/Ui.java, src/main/java/seedu/address/events/controller/JumpToListRequestEvent.java, src/main/java/seedu/address/parser/Parser.java, src/test/java/guitests/PersonSelectCommandTest.java
=> support select command #46

README.md, build.gradle
=> Clean up build.gradle #65

src/main/java/seedu/address/commons/StringUtil.java, src/main/java/seedu/address/controller/CommandBox.java, src/main/java/seedu/address/controller/HelpWindow.java, src/main/java/seedu/address/controller/MainWindow.java, src/main/java/seedu/address/controller/PersonListPanel.java, src/main/java/seedu/address/controller/ResultDisplay.java, src/main/java/seedu/address/controller/StatusBarFooter.java, src/main/java/seedu/address/controller/Ui.java, src/main/java/seedu/address/controller/UiPart.java, src/main/java/seedu/address/controller/UiPartLoader.java, src/main/resources/view/MainWindow.fxml
=> Cleanup ui

src/main/java/seedu/address/browser/BrowserPanel.java, src/main/java/seedu/address/controller/BrowserPanel.java, src/main/java/seedu/address/controller/MainWindow.java, src/main/java/seedu/address/controller/Ui.java
We can get rid of BrowserManager and make Browser a UiPart.
=> Refine browser to be a UiPart

src/main/java/seedu/address/commands/IncorrectCommand.java, src/main/java/seedu/address/commands/IncorrectCommandResult.java, src/main/java/seedu/address/controller/CommandBox.java, src/main/java/seedu/address/controller/MainWindow.java, src/main/java/seedu/address/logic/Logic.java, src/test/java/seedu/address/controller/CommandBoxTest.java, src/test/java/seedu/address/logic/LogicTest.java
=> Add a Logic class

src/main/resources/view/HelpWindow.fxml, src/test/java/guitests/HelpWindowTest.java, src/test/java/guitests/guihandles/CommandBoxHandle.java, src/test/java/guitests/guihandles/GuiHandle.java, src/test/java/guitests/guihandles/HelpWindowHandle.java, src/test/java/guitests/guihandles/MainMenuHandle.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java
=> Add GUI test for help window #70

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/parser/Parser.java, src/main/java/seedu/address/ui/BrowserPanel.java, src/main/java/seedu/address/ui/CommandBox.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/main/java/seedu/address/ui/StatusBarFooter.java, src/main/java/seedu/address/ui/Ui.java, src/main/java/seedu/address/ui/UiPart.java, src/main/java/seedu/address/ui/UiPartLoader.java, src/main/resources/view/CommandBox.fxml, src/main/resources/view/HelpWindow.fxml, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListPanel.fxml, src/main/resources/view/ResultDisplay.fxml, src/main/resources/view/StatusBarFooter.fxml, src/test/java/seedu/address/logic/LogicTest.java
=> Rename controller -> ui #24

src/main/java/seedu/address/logic/commands/AddCommand.java
=> Remove private field specification in add command help (E.g. [p]p) #101

docs/DeveloperGuide.md, docs/UsingGradle.md
=> Fix typos and grammar in DeveloperGuide.md and UsingGradle.md #96

src/main/java/seedu/address/model/person/ReadOnlyPerson.java
=> Output panel says "(private)" everytime a person is added or deleted. #99

src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java, src/main/java/seedu/address/ui/StatusBarFooter.java, src/test/java/seedu/address/logic/LogicManagerTest.java
Implementation takes advantage of the EventsCenter to check for updates to AddressBook
however when it starts up, the app is not aware of the address book's last updated (before the app starts up) date/time. 
Fixes #98
=> Implement 'Last updates timestamp' feature #98

src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/StatusBarFooter.java, src/main/java/seedu/address/ui/UiPart.java
=> NullPointerException when updating status bar #115

src/main/java/seedu/address/commons/util/CollectionUtil.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/java/seedu/address/model/tag/UniqueTagList.java
=> Fix compiler warnings #94

build.gradle, docs/DeveloperGuide.md, docs/UsingGradle.md, src/main/java/seedu/address/commons/util/UrlUtil.java, src/test/java/seedu/address/commons/util/UrlUtilTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java
=> Rename gradle task: unittests --> nonGuiTests #112

src/test/java/seedu/address/TestApp.java, src/test/java/seedu/address/commons/util/FileUtilTest.java, src/test/java/seedu/address/commons/util/XmlUtilTest.java, src/test/java/seedu/address/testutil/TestUtil.java
=> Create sandbox folder if it doesn't exist #111

docs/addressbook/Logging.md, src/main/java/seedu/address/commons/core/LogsCenter.java
Fixes #122 and #126 
Combining these 2 since they are somewhat related.
=> Set rolling file for logging #122 #126

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/SelectCommand.java
=> Update docs/error message to mention index should be a positive number #103

.settings/org.eclipse.buildship.core.prefs
Tweaked this file because Eclipse added it during the set up process, and gives an error if I remove it.
=> Tweak Gradle preferences file

src/main/java/seedu/address/commons/events/ui/ExitAppRequestEvent.java, src/main/java/seedu/address/commons/events/ui/ShowHelpRequestEvent.java, src/main/java/seedu/address/commons/util/CollectionUtil.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/model/tag/UniqueTagList.java, src/main/java/seedu/address/ui/UiManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Code quality tweaks

src/main/java/seedu/address/commons/util/AppUtil.java, src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/commons/util/UrlUtil.java, src/test/java/seedu/address/commons/core/ConfigTest.java, src/test/java/seedu/address/commons/util/AppUtilTest.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/seedu/address/commons/util/UrlUtilTest.java
=> Add some missing util tests

src/main/java/seedu/address/ui/UiManager.java, src/test/java/guitests/AddressBookGuiTest.java, src/test/java/guitests/ErrorDialogGuiTest.java, src/test/java/guitests/guihandles/AlertDialogHandle.java, src/test/java/guitests/guihandles/GuiHandle.java, src/test/java/guitests/guihandles/MainGuiHandle.java
=> Add a GUI test to test the error dialog #133

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/commons/util/StringUtilTest.java
Refined the test cases to show the usage of test case design heuristics
=> Add tests for StringUtil::containsWordIgnoreCase

src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/java/seedu/address/model/tag/UniqueTagList.java, src/main/java/seedu/address/storage/XmlSerializableAddressBook.java, src/test/java/seedu/address/testutil/TestPerson.java
Fixes #87.
Also done for `UniqueTagList`.
Closed up quite a few other holes (eg. unecessary exposure of internals) for safety.
=> Increase encapsulation of UniquePersonList #87

docs/DeveloperGuide.md
=> Developer guide -> sequence diagram description -> typo #163

src/main/java/seedu/address/commons/util/FxViewUtil.java, src/main/java/seedu/address/ui/CommandBox.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/main/java/seedu/address/ui/StatusBarFooter.java, src/main/java/seedu/address/ui/UiPart.java, src/main/java/seedu/address/ui/UiPartLoader.java
=> UiParts should not store a reference to the primaryStage #183

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/commons/core/UnmodifiableObservableList.java, src/main/java/seedu/address/model/person/Address.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java
=>  checkstyle: check for trailing whitespace  #179

docs/DeveloperGuide.md
=> Fix language errors in developer guide #197

src/main/java/seedu/address/model/person/ReadOnlyPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml, src/test/java/guitests/guihandles/PersonCardHandle.java
=> Add background color to tags #173

build.gradle
Fixes #161 
Still need some testing and verification.
=> Include test code in coverage analysis #161

src/test/java/guitests/guihandles/AlertDialogHandle.java, src/test/java/guitests/guihandles/GuiHandle.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java, src/test/java/guitests/guihandles/ResultDisplayHandle.java
=> Make `GuiHandle::getNode()` return a `<T extends Node> T` #219

src/test/java/seedu/address/commons/util/CollectionUtilTest.java
Fixes #233 
Code adapted from addressbook-level2
=> Add unit test for CollectionUtil class #233

build.gradle
Reversing #161 as it resulted in an incorrect drop in coverage level reported
=> Reverse #161 (Include test code in coverage analysis)

src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java, src/test/java/seedu/address/testutil/TypicalTestPersons.java
=> Rework how TypicalTestPersons exposes its persons #221

src/main/java/seedu/address/commons/core/UnmodifiableObservableList.java, src/main/java/seedu/address/commons/events/ui/IncorrectCommandAttemptedEvent.java, src/main/java/seedu/address/logic/commands/Command.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/commons/util/ConfigUtilTest.java, src/test/java/seedu/address/testutil/TestUtil.java
=> Resolve Eclipse warnings #223

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/tag/UniqueTagList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/guitests/SampleDataTest.java, src/test/java/seedu/address/testutil/TypicalTestPersons.java
Fixes #60 
If no save file is detected, sample data is loaded into memory.
File is not created with the sample data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/se-edu/addressbook-level4/226)
=> Show some sample data when the app is run for the first time #60

config/checkstyle/checkstyle.xml
=> checkstyle: check for unused import #252

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/commons/core/LogsCenter.java, src/main/java/seedu/address/commons/core/UnmodifiableObservableList.java, src/main/java/seedu/address/storage/XmlAddressBookStorage.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java
=> checkstyle: ensure overloaded methods are grouped together #229

config/checkstyle/checkstyle.xml
=> checkstyle: fix module name error #276

src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Name.java, src/test/java/seedu/address/model/person/AddressTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/NameTest.java, src/test/java/seedu/address/model/person/PhoneTest.java
=> Add unit tests for person's fields classes #172

build.gradle, docs/TestDocument.adoc, docs/UsingGradle.md, docs/stylesheets/asciidoctor.css, docs/stylesheets/gh-pages.css
=> Add asciidoctor to Gradle #269

src/test/java/seedu/address/testutil/TestUtil.java
Closes #222 
Removed the following unused methods:
* TestUtil#main()
* TestUtil#isHeadlessEnvironment()
* TestUtil#captureScreenShot()
* TestUtil#descOnFail()
* TestUtil#setFinalStatic()
* TestUtil#initRuntime()
* TestUtil#tearDownRuntime()
* TestUtil#getPrivateMethod()
* TestUtil#renameFile()
* TestUtil#getSceneMidPoint()
* TestUtil#getScenePos()
* TestUtil#getSceneMaxX()
* TestUtil#getSceneMaxY()
* TestUtil#getLastElement()
* TestUtil#replacePersonFromList()
=> Remove unused code in TestUtil #222

src/main/resources/view/Extensions.css
=> Blank person cards should not have alternating colours #301

docs/DeveloperGuide.md
=> Add explicit reference to coding style guidelines in docs #207

src/main/java/seedu/address/ui/CommandBox.java, src/test/java/guitests/CommandBoxTest.java
=> CommandBox stays red even after correct input is entered #296

docs/DeveloperGuide.md, docs/UserGuide.md
=> HTML anchors in UserGuide.md DeveloperGuide.md all broken #340

src/main/java/seedu/address/commons/core/LogsCenter.java
=> Fix typo in LogsCenter#getLogger(...) header comment #344

build.gradle
=> All gui tests are failing #353

.travis.yml
=> Travis CI: cache dependencies #342

config/checkstyle/checkstyle.xml
=> Checkstyle: add ArrayTypeStyle rule #319

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/core/EventsCenter.java, src/main/java/seedu/address/logic/commands/SelectCommand.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/ui/CommandBox.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/StatusBarFooter.java, src/main/java/seedu/address/ui/UiManager.java, src/test/java/guitests/AddressBookGuiTest.java, src/test/java/seedu/address/TestApp.java, src/test/java/seedu/address/storage/StorageManagerTest.java
=> Checkstyle: add DeclarationOrder rule #319

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/ui/BrowserPanel.java
=> Checkstyle: add CommentsIndentation rule #319

config/checkstyle/checkstyle.xml
=> Checkstyle: add EmptyCatchBlock rule #319

config/checkstyle/checkstyle.xml, src/test/java/seedu/address/commons/util/XmlUtilTest.java
=> Checkstyle: fix MethodName supplied expression #319

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/commons/core/LogsCenter.java, src/main/java/seedu/address/commons/util/StringUtil.java
=> Checkstyle: fix NeedBraces properties #319

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/data/XmlUtilTest/validAddressBook.xml, src/test/java/guitests/EditCommandTest.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/testutil/TestUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Remove uses of real domain names #371

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Checkstyle: prevent upper case abbreviations in names #319

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/model/AddressBook.java
=> Checkstyle: enforce @clause order #319

config/checkstyle/checkstyle.xml
=> Checkstyle: require default branch in switch statements #319

src/main/java/seedu/address/commons/util/IndexUtil.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/SelectCommand.java, src/test/java/guitests/DeleteCommandTest.java, src/test/java/guitests/EditCommandTest.java, src/test/java/guitests/SelectCommandTest.java, src/test/java/seedu/address/commons/util/IndexUtilTest.java, src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java, src/test/java/seedu/address/testutil/TestUtil.java
=> Implement a IndexUtil#oneToZeroIndex() abstraction #293

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/commons/events/storage/DataSavingExceptionEvent.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/storage/XmlAdaptedTag.java, src/test/java/guitests/AddressBookGuiTest.java, src/test/java/guitests/EditCommandTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Checkstyle: enforce final keyword or encapsulation for class variables #319

src/test/java/seedu/address/logic/commands/EditCommandIntegrationTest.java, src/test/java/seedu/address/testutil/PersonUtil.java
Part of #254 
Ready for review.
=> Add Integration Tests for EditCommand #254

src/main/java/seedu/address/model/person/Phone.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/model/person/PhoneTest.java
=> Update Phone's regex to reject numbers shorter than 3 digits #286

src/test/java/seedu/address/logic/LogicManagerTest.java
=> Replace LogicManagerTest#generatePersonWithName() with PersonBuilder #389

src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
This is part of #172.
```
AddCommand does not have its own unit test.
Let's add a unit test for AddCommand.
```
=> Add unit tests for AddCommand

src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/SelectCommandParser.java
=> ParserUtil: use exceptions for error handling #303

src/main/java/seedu/address/model/tag/UniqueTagList.java
=> UniqueTagList: Add assertions to check all tags are unique #411

src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/EditCommandIntegrationTest.java
=> Fix minor bug in EditCommandIntegrationTest #428

src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
=> Teach Parser to enforce spaces between fields #406

src/main/java/seedu/address/logic/commands/EditCommand.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/testutil/EditCommandTestUtil.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
=> Create Parser Tests for EditCommand #254

src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> Create unit tests for ParserUtil#parseX() #401

src/test/java/guitests/guihandles/GuiHandle.java
=> GuiHandle#setTextField(String, String) should call Gui methods on JavaFx threads #433

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> Create unit tests for ParserUtil#parseIndex() #401

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> StringUtil#isUnsignedInteger(String): Fix unhandled NFE #436

src/main/java/seedu/address/ui/HelpWindow.java
=> Fix HelpWindow online user guide URL #469

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java
=> Model#updatePerson(...): Change parameter from Index to ReadOnlyPerson #468

src/test/java/seedu/address/logic/commands/ExitCommandTest.java
=> Add tests for ExitCommand #327

src/test/java/seedu/address/logic/commands/HelpCommandTest.java
=> Add tests for HelpCommand #327

src/test/java/seedu/address/logic/commands/ClearCommandTest.java
=> Add tests for ClearCommand #327

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java, src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/testutil/AddressBookBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Extract exceptions in UniquePersonList #476

src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
=> Add tests for DeleteCommandParser #327

src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java
=> Add more tests for EditCommand #254 

docs/LearningOutcomes.adoc, docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/guitests/EditCommandTest.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/testutil/PersonUtil.java
=> Add Prefix "n/" for specifying names #467

src/test/java/seedu/address/logic/commands/ListCommandTest.java
=> Add tests for ListCommand

src/test/java/seedu/address/logic/commands/SelectCommandTest.java
=> Add tests for SelectCommand #327

src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
=> Add tests for SelectCommandParser #327

src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
=> Add AddCommandIntegrationTest #327

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/LogicManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java
=> Remove redundant parameter in LogicManager constructor #437

src/test/java/guitests/GuiRobot.java, src/test/java/seedu/address/testutil/TestUtil.java
```
GuiRobot#push(KeyCodeCombination) and TestUtil#scrub(KeyCodeCombination)
are not used by any classes.
Let's remove them.
```
=> Remove unused test methods

src/main/java/seedu/address/commons/util/CollectionUtil.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/test/java/seedu/address/commons/util/CollectionUtilTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
=> Change EditPersonDescriptor parameters to be non-Optional #480

src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java
=> Add tests for DeleteCommand

src/test/java/guitests/AddressBookGuiTest.java, src/test/java/guitests/ErrorDialogGuiTest.java, src/test/java/guitests/guihandles/AlertDialogHandle.java, src/test/java/guitests/guihandles/BrowserPanelHandle.java, src/test/java/guitests/guihandles/CommandBoxHandle.java, src/test/java/guitests/guihandles/GuiHandle.java, src/test/java/guitests/guihandles/HelpWindowHandle.java, src/test/java/guitests/guihandles/MainMenuHandle.java, src/test/java/guitests/guihandles/MainWindowHandle.java, src/test/java/guitests/guihandles/PersonCardHandle.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java, src/test/java/guitests/guihandles/ResultDisplayHandle.java, src/test/java/guitests/guihandles/StatusBarFooterHandle.java
Part of #459.
Proposed merge commit messages:
```
GuiHandle contains unnecessary parameters in its constructor. It also
contains methods that are more specialized to individual components.
Let's remove these constructor parameters, and move the methods to their
appropriate component handle classes.
```
=> Clean up GuiHandle #459

src/test/java/guitests/AddCommandTest.java, src/test/java/guitests/ClearCommandTest.java, src/test/java/guitests/DeleteCommandTest.java, src/test/java/guitests/EditCommandTest.java, src/test/java/guitests/FindCommandTest.java, src/test/java/guitests/SelectCommandTest.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java
Part of #459.
```
PersonListPanelHandle contains an unused method. The logic for some
methods in PersonListPanelHandle can also be improved.
Let's tidy up PersonListPanelHandle by:
* Removing unused or unnecessary methods
* Throwing more specific exceptions
* Improving the logic of various methods
```
=> Clean PersonListPanelHandle #459

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/SelectCommand.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/SelectCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java, src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
=> Change visibility modifier of DeleteCommand & SelectCommand targetIndex #527

src/main/java/seedu/address/logic/commands/FindCommand.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
=> Add FindCommandTest and FindCommandParserTest #327

src/main/java/seedu/address/logic/CommandHistory.java
=> CommandHistory: Change userInputHistory implementation to LinkedList #532

src/main/java/seedu/address/ui/CommandBox.java, src/test/java/guitests/CommandBoxTest.java
=> CommandBox: Reset style class upon keypress #529

build.gradle, src/test/java/guitests/guihandles/PersonCardHandle.java, src/test/java/seedu/address/testutil/TestUtil.java, src/test/java/seedu/address/ui/PersonCardTest.java, src/test/java/seedu/address/ui/testutil/StageRule.java, src/test/java/seedu/address/ui/testutil/UiPartRule.java
Fixes ~~172~~ #280.
```
The GUI tests are system tests, which would make use of the main
application and create all of the GUI parts.
There is no easy way to unit test the GUI parts without launching the
entire application. Therefore, there are no unit tests for GUI parts.
Let's create a testing architecture for testing individual GUI parts,
and let's create PersonCard unit test as a demonstration of the testing
architecture.
```
=> Add unit tests for PersonCard class

src/main/java/seedu/address/MainApp.java
=> MainApp: Update version to 1.4 #249

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/HistoryCommand.java, src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
=> HistoryCommand: Returns previous commands in reverse chronological order #534

src/main/java/seedu/address/model/tag/UniqueTagList.java
=> UniqueTagList: Remove unused constructors #539

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/logic/commands/SelectCommandTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
=> Model filtering not easily extensible #334

src/main/java/seedu/address/logic/parser/ParserUtil.java
=> ParserUtil: Update header comments on Optional usage #557

src/main/java/seedu/address/ui/BrowserPanel.java, src/main/java/seedu/address/ui/HelpWindow.java, src/test/java/guitests/StatusBarFooterTest.java, src/test/java/guitests/guihandles/BrowserPanelHandle.java, src/test/java/guitests/guihandles/HelpWindowHandle.java, src/test/java/guitests/guihandles/WebViewUtil.java, src/test/java/seedu/address/testutil/EventsUtil.java, src/test/java/seedu/address/ui/BrowserPanelTest.java, src/test/java/seedu/address/ui/CommandBoxTest.java, src/test/java/seedu/address/ui/GuiUnitTest.java, src/test/java/seedu/address/ui/HelpWindowTest.java, src/test/java/seedu/address/ui/PersonCardTest.java, src/test/java/seedu/address/ui/PersonListPanelTest.java, src/test/java/seedu/address/ui/ResultDisplayTest.java, src/test/java/seedu/address/ui/StatusBarFooterTest.java
Part of #172. Also fixes #263.
Prerequisite: #260.
```
Our GUI tests in the codebase are system tests.
There are no unit tests for each GUI component in the application.
Let's add unit test for GUI components.
```
=> Add unit tests for GUI #172

src/test/java/guitests/AddCommandTest.java, src/test/java/guitests/AddressBookGuiTest.java, src/test/java/guitests/DeleteCommandTest.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java, src/test/java/seedu/address/TestApp.java, src/test/java/seedu/address/commons/util/XmlUtilTest.java, src/test/java/seedu/address/model/UnmodifiableObservableListTest.java, src/test/java/seedu/address/testutil/Assert.java, src/test/java/seedu/address/testutil/TestUtil.java
Fixes #295. In fixing #295, we happen to fix #348 as well.
```
TestUtil is a class with low cohesion as it contains methods that
are unrelated to each other.
This breaks the Single Responsibility Principle, whereby each class
is supposed to have only one responsibility.
Let's split up the methods into different classes to improve the
cohesion of TestUtil. Also, let's do a general cleanup of TestUtil
by removing unused methods etc.
```
=> Clean up TestUtil #295 #348

src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/logic/commands/SelectCommandTest.java
=> XCommandTest: Move showFirstPersonOnly(Model) #561

src/test/java/seedu/address/TestApp.java, src/test/java/seedu/address/logic/UndoRedoStackUtil.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/testutil/AddressBookBuilder.java, src/test/java/seedu/address/testutil/Assert.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Fix part of the issue face in #379 
Full result (with the Checkstyle updated) is at [here](https://github.com/CS2103R-Eugene-Peh/addressbook-level4/commits/319-add-JavadocMethod-and-JavadocType)
=> Test folder: add missing API header comments #379

src/test/java/guitests/AddCommandTest.java, src/test/java/guitests/AddressBookGuiTest.java, src/test/java/guitests/ClearCommandTest.java, src/test/java/guitests/DeleteCommandTest.java, src/test/java/guitests/EditCommandTest.java, src/test/java/guitests/FindCommandTest.java, src/test/java/guitests/SampleDataTest.java, src/test/java/guitests/guihandles/PersonCardHandle.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java, src/test/java/guitests/guihandles/ResultDisplayHandle.java, src/test/java/guitests/guihandles/StageHandle.java, src/test/java/seedu/address/ui/PersonCardTest.java, src/test/java/seedu/address/ui/PersonListPanelTest.java, src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
=> Clean up Handle classes #459

build.gradle, docs/DeveloperGuide.adoc, docs/UserGuide.adoc, docs/team/johndoe.adoc
=> Add a sample portfolio page #584

build.gradle, docs/johndoe.adoc
Temporary fix for the css not working on gh-pages
=> Move johndoe.adoc to the docs folder

docs/DeveloperGuide.adoc
=> Dev guide: remove author names from sections #588

build.gradle, config/checkstyle/checkstyle.xml, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/model/ReadOnlyAddressBook.java, src/main/java/seedu/address/model/person/Address.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java, src/test/java/seedu/address/commons/util/FileUtilTest.java, src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java, src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
=> Upgrade Checkstyle to version 8.1 #604

src/test/java/guitests/AddCommandTest.java, src/test/java/guitests/AddressBookGuiTest.java, src/test/java/guitests/ClearCommandTest.java, src/test/java/guitests/EditCommandTest.java, src/test/java/guitests/ErrorDialogGuiTest.java, src/test/java/guitests/FindCommandTest.java, src/test/java/guitests/GuiRobot.java, src/test/java/guitests/SelectCommandTest.java, src/test/java/guitests/guihandles/BrowserPanelHandle.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java, src/test/java/seedu/address/testutil/EventsUtil.java, src/test/java/seedu/address/ui/BrowserPanelTest.java, src/test/java/seedu/address/ui/PersonListPanelTest.java, src/test/java/seedu/address/ui/ResultDisplayTest.java, src/test/java/seedu/address/ui/StatusBarFooterTest.java, src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
=> Clean up GUI tests related classes #559

src/main/java/seedu/address/MainApp.java
=> MainApp: Update version number #575

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/UndoableCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
=> Model: Remove updateFilteredListToShowAll() #519

src/main/java/seedu/address/ui/BrowserPanel.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/main/java/seedu/address/ui/StatusBarFooter.java, src/test/java/guitests/guihandles/PersonListPanelHandle.java
=> Fix bugs in GUI related classes #623

config/checkstyle/checkstyle.xml, config/checkstyle/suppressions.xml, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/core/LogsCenter.java, src/main/java/seedu/address/commons/events/BaseEvent.java, src/main/java/seedu/address/commons/util/FileUtil.java, src/main/java/seedu/address/commons/util/JsonUtil.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/tag/UniqueTagList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/ui/CommandBox.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/UiManager.java, src/test/java/guitests/AddCommandTest.java, src/test/java/guitests/FindCommandTest.java, src/test/java/guitests/SelectCommandTest.java, src/test/java/seedu/address/commons/util/CollectionUtilTest.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
=> Checkstyle: enforce header comments on classes and methods #319

docs/DeveloperGuide.adoc
=> Developer Guide: Document previewing of .adoc files #603

config/checkstyle/checkstyle.xml
Addition to #319 
Ready for review
=> Checkstyle: enforce single statement per line #319

docs/AboutUs.adoc
=> Update AboutUs.adoc #660

build.gradle
=> Gradle configuration: Fix nonGuiTests #666

src/test/java/guitests/SampleDataTest.java
=> SampleDataTest: Fix buggy implementation of getDataFileLocation() #678

docs/DeveloperGuide.adoc
=> DeveloperGuide: update converting docs to PDF format

config/checkstyle/checkstyle.xml, src/test/java/seedu/address/commons/core/VersionTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Checkstyle: enforce one variable declaration per line #319

src/test/java/guitests/HelpWindowTest.java
=> HelpWindowTest: Write header comments concerning possible test failure #680

docs/DeveloperGuide.adoc
=> DeveloperGuide: Update instructions on setting up #672

docs/DeveloperGuide.adoc, docs/UsingCheckstyle.adoc, docs/UsingTravis.adoc
Extracted/reordered/rephrased some stuff to improve readability.
=> docs: restructure dev docs

docs/UserGuide.adoc
Fixes #698 
```
Some parts of the UserGuide are inconsistent, and some segments can be
written clearer.
Let's update it.
```
=> Tweaks to User Guide #698

docs/DeveloperGuide.adoc
=> Developer Guide: add instructions for manual testing #777

docs/UserGuide.adoc
=> User Guide: add an introduction #779

README.adoc
=> README: acknowledge use of third-party libraries #781

docs/DeveloperGuide.adoc
=> Developer Guide: specify target user profile and value proposition #775

src/main/resources/view/DarkTheme.css
=> Ui: fix default PersonListPanel background color #415

src/test/java/guitests/guihandles/StageHandle.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/systemtests/AddressBookSystemTest.java, src/test/java/systemtests/FindCommandSystemTest.java
fixes #814
Replaced assert in a few test locations:
- StageHandle.java
- CommandtestUtil.java
- DeleteCommandTest.java
- AddressBookSystemTest.java
- FindCommandSystemTest.java
=> Test: replace all asserts with JUnit Assertion #814

README.adoc
```
Let the world know where all the cool people hang out.
```
=> README.adoc: add Gitter badge

src/main/java/seedu/address/commons/core/LogsCenter.java, src/main/java/seedu/address/commons/util/CollectionUtil.java, src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/XmlAdaptedPerson.java
Fixes #634 
These are the verbose loops found in the **main** folder:
```
grep -rn "for (" main/
main/java/seedu/address/model/person/UniquePersonList.java:91:        for (final Person person : persons) {
main/java/seedu/address/model/util/SampleDataUtil.java:46:            for (Person samplePerson : getSamplePersons()) {
main/java/seedu/address/model/util/SampleDataUtil.java:60:        for (String s : strings) {
main/java/seedu/address/logic/parser/ArgumentTokenizer.java:39:        for (Prefix prefix : prefixes) {
main/java/seedu/address/logic/parser/ArgumentTokenizer.java:104:        for (int i = 0; i < prefixPositions.size() - 1; i++) {
main/java/seedu/address/logic/parser/ParserUtil.java:163:        for (String tagName : tags) { …
```
=> Replace all verbose loops with lambda expression #634

build.gradle
=> Tidy up build.gradle #706

src/test/java/seedu/address/ui/HelpWindowTest.java
=> Fix stalling HelpWindowTest

src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/systemtests/AddCommandSystemTest.java, src/test/java/systemtests/EditCommandSystemTest.java
=> Refactor PersonBuilder constructor to use TypicalPersons as argument #855

src/main/java/seedu/address/logic/parser/ParserUtil.java
=> ParserUtil: remove unused field MESSAGE_INSUFFICIENT_PARTS

src/test/java/seedu/address/testutil/TestUtil.java, src/test/java/systemtests/SelectCommandSystemTest.java
=> Update TestUtil to use filteredList #829

config/checkstyle/checkstyle.xml, src/main/java/seedu/address/commons/util/JsonUtil.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/storage/XmlAddressBookStorage.java, src/test/java/guitests/GuiRobot.java, src/test/java/seedu/address/commons/core/VersionTest.java, src/test/java/seedu/address/commons/util/AppUtilTest.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/systemtests/ClearCommandSystemTest.java
=> checkstyle: add SingleSpaceSeparator

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/systemtests/EditCommandSystemTest.java
Can't find much of an overarching theme to the commits, so
no merge commit, commits are standalone.
=> Rename updatePerson(...) to setPerson(...)

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/Ui.java, src/main/java/seedu/address/ui/UiManager.java, src/test/java/seedu/address/ui/MainWindowCloseTest.java
=> MainApp: don't forcefully terminate the application on exit

README.adoc, build.gradle, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/guitests/guihandles/PersonCardHandle.java, src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
```
Remove Guava dependency to make application maintenance easier.
```
=> Remove Guava dependency
