- src/test/java/guitests/guihandles/GuiHandle.java
Fixes #53 
Speeds up tests about 2m 50s to 2m 10s.
> GUI tests: use setText instead of write #53

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
PMD discourages use of non-static initializer blocks as they are 'rarely used and confusing to the reader'
> Remove non-static initializers

- build.gradle
- docs/UsingGradle.md
Fixes #177 
The `run` and `runShadow` tasks provide a convenient way for developers
to run the built application from its *.class files or the built fat JAR
respectively.
This is accomplished using the application plugin[1] which implements
the 'run' task.
The shadow plugin, which we already use, will automatically detect the
`application` plugin and will integrate with it[2], providing the
`runShadow` task. It also knows that `mainClassName` should be used
as the "Main-Class" of the JAR manifest, so we don't need to specify
that anymore.
[1] https://docs.gradle.org/current/userguide/application_plugin.html
[2] http://imperceptiblethoughts.com/shadow/#integrating_with_application_plugin
> build.gradle: add `run` and `runShadow` tasks #177

- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/resources/view/StatusBarFooter.fxml
Fixes #188 
StatusBarFooter currently constructs and sets up its StatusBar controls
using pure code.
The StatusBar control is actually a real control that can be initialized
directly in the FXML file. We can avoid placeholder elements and make
things simpler by just doing that.
Now, one may think: "This means Scene Builder cannot edit this FXML file
any more!", since the StatusBar control comes from controlsfx, which is
not supported by Scene Builder by default. However,
1. Scene Builder can actually be configured[1] to support the custom
controls from controlsfx, allowing it to edit the FXML file.
2. Having too many placeholder nodes, and constructing the actual scene
graph in code, kind of defeats the advantage of FXML which is to
construct the scene graph declaratively without code. …
> Construct StatusBarFooter in FXML fully #188

- config/checkstyle/checkstyle.xml
Fixes #191 
Checking out this repo on a Windows machine with a vanilla Git config,
then running `gradlew.bat checkstyleMain` gives the following errors:
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\MainApp.java:0: File does not end with a newline. [NewlineAtEndOfF
ile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\ComponentManager.java:0: File does not end with a new
line. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\
seedu\address\commons\core\Config.java:0: File does not end with a newline. [New
lineAtEndOfFile]
[ant:checkstyle] [ERROR] C:\Users\pyokagan\pyk\addressbook-level4\src\main\java\ …
> checkstyle: NewlineAtEndOfFile errors with vanilla Git config on Windows #191

- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/guitests/AddressBookGuiTest.java
- src/test/java/guitests/HelpWindowTest.java
- src/test/java/guitests/guihandles/BrowserPanelHandle.java
- src/test/java/guitests/guihandles/CommandBoxHandle.java
- src/test/java/guitests/guihandles/HelpWindowHandle.java
- src/test/java/guitests/guihandles/MainGuiHandle.java
- src/test/java/guitests/guihandles/ResultDisplayHandle.java
Fixes #149 
This issue may be caused by a JavaFX bug, as suggested here https://bugs.openjdk.java.net/browse/JDK-8131666.
It's because TextField and TextAreas in CommandBox and ResultDisplay will consume F1 keyevents. As a result, the accelerators will not be fired up.
The discussion in the post shows that the bug will only be fixed in later version of JDK (though it's openJDK but I guess it should be similar case for JDK itself.)
Thus in this PR, what I implemented is just a workaround.
- Explicitly bind F1 keyevents to open help window for CommandBox TextField and ResultDisplay TextArea using `addEventFilter`
- Remove `personListPanel.clickOnListView()` in `HelpWindowTest` because now the focus doesn't have to be in the person list for F1 accelerator to work.
Ready for review
> Support F1 accelerator even when the focus is not in the list #149

- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyAddressBook.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/main/java/seedu/address/model/tag/UniqueTagList.java
- src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
- src/test/java/guitests/AddressBookGuiTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/testutil/TestUtil.java
Fixes #190 
[ReadOnlyAddressBook](https://github.com/se-edu/addressbook-level4/blob/61b1f6fa5d259677efcd8df61b73b7569b7d5715/src/main/java/seedu/address/model/ReadOnlyAddressBook.java#L16-L18) currently exposes its underlying `UniqueTagList` and `UniquePersonList` objects via `getUniqueTagList()` and `getUniquePersonList()` respectively. Problem is, [UniqueTagList](https://github.com/se-edu/addressbook-level4/blob/61b1f6fa5d259677efcd8df61b73b7569b7d5715/src/main/java/seedu/address/model/tag/UniqueTagList.java#L73-L109) and [UniquePersonList](https://github.com/se-edu/addressbook-level4/blob/61b1f6fa5d259677efcd8df61b73b7569b7d5715/src/main/java/seedu/address/model/person/UniquePersonList.java#L31-L60) both contain mutating methods, so `ReadOnlyAddressBook` is not actually read-only. …
> Make ReadOnlyAddressBook truly read-only #190

- docs/UserGuide.md
- src/main/java/seedu/address/commons/util/CollectionUtil.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/Parser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/test/java/guitests/EditCommandTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TestPerson.java
Fixes #141 
Ready for review.
* [1/6] [create constants for keys (to be used in HashMap for EditCommand) and make Person mutable.](https://github.com/se-edu/addressbook-level4/pull/209/commits/2df9e1b9427c95c334680f19c553c9755be14bf7)
* [2/6] [create EditCommand & update Parser and ArgumentTokenizer.](https://github.com/se-edu/addressbook-level4/pull/209/commits/24daab843f7baee1378612e049d2076038d61e13)
* [3/6] [update Model package (ModelManager, Model, AddressBook, UniquePersonList) to allowing editing.](https://github.com/se-edu/addressbook-level4/pull/209/commits/1270bdb4998f36e39bb1670b12384b6d61db1a55)
* [4/6] [create NoArgumentException](https://github.com/se-edu/addressbook-level4/pull/209/commits/029cd8779cb0dca7874c3c711f0ca70078925a4c)
* [5/6] [update User Guide to include …
> User can edit a person's details #141

- src/main/java/seedu/address/ui/HelpWindow.java
Closes #217 
This points the URL of the help window to a more aesthetically pleasing document rather than the current one pointing directly to the markdown in github
> Update URL of help window #217

- .travis.yml
- build.gradle
Fixes #204.
Commit message 94c738b:
> Gradle utilises different levels for logging (see
> https://docs.gradle.org/current/userguide/logging.html).
> 
> .travis.yml was set to execute gradle with '-i'. This meant that log
> messages with 'INFO' level and above are generated to stdout. Such
> 'INFO' messages are generally unhelpful, as they do not provide any
> additional meaningful information not already given by test failure
> messages, and they pollute the log due to their large quantity.
> 
> As such, '-i' is removed so that only messages on 'LIFECYCLE' level,
> 'WARNING' level and above are generated (i.e. the 'INFO' level is
> omitted) - this is the default behaviour of Gradle.
> Make Travis CI output less verbose #204

- src/main/java/seedu/address/commons/util/CollectionUtil.java
- src/main/java/seedu/address/model/tag/UniqueTagList.java
- src/test/java/seedu/address/commons/util/CollectionUtilTest.java
Previously, assertNoNullElements wasn't even working as intended at all. The
original intention of this method was to ensure each element of the given
collection was non-null. However, by simply doing
'assert !isAnyNull(Collection)', the collection was parsed as an Object, instead
of an Object[]. Meaning it only checked if the collection reference was
null rather than its actual elements.
This commit both fixes this issue and refactors it into an overloaded method.
By refactoring the method to return boolean instead of void, we shift the
assertion responsibility outwards to wherever this method is called. Forcing
the explicit usage of the 'assert' keyword thus making it clearer that an
assertion is actually happening.
As [requested](https://github.com/se-edu/addressbook-level4/pull/248#iss …
> CollectionUtil: refactor assertNoNullElements -> isAnyNull(Collection)

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Fixes #235 
Collecting a list of small cleanups that can be made.
Cleanups have also been applied to 97c34f2b96ec34b3afd93876f3eda12455759c91 that addresses #141.
- `getPreamble()`: Rather than returning `Optional.empty()`, an empty string can be returned instead. (With defensive programming, callers will need to check for empty string anyway).
- `getAllValues()`: Rather than returning `Optional.empty()`, an empty list can be returned instead. (With defensive programming, callers will need to check for an empty list anyway). This has the side benefit of removing the `toSet()` helper in `Parser`.
Use of regular expressions that are less readable than their less fancy counterparts:
- `PERSON_INDEX_ARGS_FORMAT` can be replaced with `String.isEmpty()`. Actually, I think …
> Parser and ArgumentTokenizer cleanups #235

- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/test/java/guitests/AddressBookGuiTest.java
- src/test/java/guitests/CommandBoxTest.java
- src/test/java/guitests/StatusBarFooterTest.java
- src/test/java/guitests/guihandles/CommandBoxHandle.java
- src/test/java/guitests/guihandles/MainGuiHandle.java
- src/test/java/guitests/guihandles/StatusBarFooterHandle.java
Fixes #114 
Current StatusBarFooterTest includes
- after a successful command, the sync status text has been updated
- after an invalid command, the sync status text is not updated
Some issues:
- only tested AddCommand.
Testing for save location in the status bar can be added later in [another PR](https://github.com/se-edu/addressbook-level4/pull/212) using SaveAsCommand, but some methods (e.g `getSaveLocation`) have already been included in this PR.
Ready for review.
> Let's add GUI tests to verify the 'last updated' feature of the status
bar footer.
> Update GUI tests to verify 'last updated' feature #114

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/commons/core/Config.java
- src/main/java/seedu/address/model/UserPrefs.java
- src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
- src/main/java/seedu/address/storage/StorageManager.java
- src/main/java/seedu/address/storage/UserPrefsStorage.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/data/ConfigUtilTest/ExtraValuesConfig.json
- src/test/data/ConfigUtilTest/TypicalConfig.json
- src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
- src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
- src/test/java/seedu/address/TestApp.java
- src/test/java/seedu/address/commons/core/ConfigTest.java
- src/test/java/seedu/address/commons/util/ConfigUtilTest.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
Fixes #213 
~Replace `ConfigUtil` with `ConfigStorage` whose functionality is similar to `JsonUserPrefsStorage` for `UserPrefs`.~
~`ConfigStorage` knows what is the current file path of the config, and provides methods for read and save the config, thus it supports updating config at runtime by calling `configStorage.saveConfig(config);` before app exits. (see `MainApp.java`)~
Changes:
- Move addressBookFilePath and addressBookName from` Config` to `UserPrefs`
- Fix JSON test data.
- Fix tests. `ConfigTest`, `ConfigUtilTest` and `JsonUserPrefsStorageTest`
- Add `setAddressBookPath(String addressBookPath)` to `Storage` interface.
- Implement the new interface method in `StorageManager`.
- Fix the initialization steps (e.g. setup `UserPrefs`, use `UserPrefs` to get addressBookFilePath …
> Allow updating addressBookPath and addressBookName at runtime. #213

- src/main/resources/view/PersonListCard.fxml
Resolves #323 
Before:
After: (Index modified)
> Index is cut off when names are too long for PersonCard #323

- src/main/java/seedu/address/ui/PersonCard.java
Closes #336 
This PR does not resolve the issue. It merely documents the fact that there exists such reserved keywords in JavaFX that cannot be used for UI elements' identification.
> Cannot add a label called `location` in person card #336

- src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
- src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Fixes #351 
- Comments in `ArgumentTokenizer` list prefixes in an outdated format (`/t` instead of the current `t/`)
- `ArgumentTokenizerTest` doesn't have tests for the current prefix format.
> Outdated prefixes in ArgumentTokenizer #351

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/ReadOnlyPerson.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/XmlAdaptedPerson.java
- src/test/java/guitests/guihandles/PersonCardHandle.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TestPerson.java
- src/test/java/seedu/address/testutil/TestUtil.java
Fixes #291.
As recommended by Paul in https://github.com/se-edu/addressbook-level4/pull/313#issuecomment-284239905, a `Set<Tag>` is suitable for replacing the return type of `ReadOnlyPerson#getTags()`. We can also gain immutability by using `Collections.unmodifiableSet(Set<T>)`.
```
ReadOnlyPerson#getTags() returns a mutable UniqueTagList.
This makes it possible for outside objects to modify the tags of
ReadOnlyPerson, violating the constraint that it is supposed to be
readonly.
Let's change ReadOnlyPerson#getTags() to return a Set<Tag>
created using Collections.unmodifiableSet(Set<T>) so that
callers are not allowed to modify the Tags returned.
```
> Make ReadOnlyPerson truly read-only #291

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
Closes #306
```
Parsing the add command string into a Person object
is split between the AddCommandParser and the AddCommand.
It is more cohesive if the said parsing is done entirely
by the AddCommandParser itself.
Let's modify the construction of add command as follows:
* Add an explicit check for empty prefixes and remove the use of
NoSuchElementException to detect missing prefixes.
* Make AddCommandParser do the parsing and create a
fully parsed Person object.
* Make AddCommand's constructor accept a fully parsed
ReadOnlyPerson.
```
> Move all parsing from AddCommand to AddCommandParser #306

- src/main/resources/view/BrowserPanel.fxml
- src/main/resources/view/CommandBox.fxml
- src/main/resources/view/HelpWindow.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/PersonListPanel.fxml
- src/main/resources/view/ResultDisplay.fxml
- src/main/resources/view/StatusBarFooter.fxml
Closes #231 
Propsed merge commit message:
```
The FXML files are deeply nested with unnecessary parent elements.
There are also multiple conflicting coding styles that exists within
the same file.
This makes the files hard to read and navigate. Furthermore, the
differing coding styles in the same file makes the whole file
inconsistent.
Let's modify the FXML files as follows:
* Change indentations to 2 spaces in all FXML files as these files
tends to have deep nesting
* Remove all star imports and reorder the rest in alphabetical
order in all FXML files
* Remove unnecessary parent elements to reduce the nesting in
all FXML files
* Remove all unnecessary CSS style sheet imports except those
in MainWindow.fxml
* Wrap long attributes into multiple lines and add white spaces
in …
```
> Simplify FXML files #231

- config/checkstyle/checkstyle.xml
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/main/java/seedu/address/model/tag/UniqueTagList.java
- src/test/java/seedu/address/ui/TestFxmlObject.java
> Checkstyle: enforce separators' placement in line wraps #319

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/Prefix.java
- src/test/java/guitests/AddCommandTest.java
- src/test/java/guitests/ClearCommandTest.java
- src/test/java/guitests/CommandBoxTest.java
- src/test/java/guitests/DeleteCommandTest.java
- src/test/java/guitests/EditCommandTest.java
- src/test/java/guitests/FindCommandTest.java
- src/test/java/guitests/SelectCommandTest.java
- src/test/java/guitests/guihandles/CommandBoxHandle.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/EditCommandIntegrationTest.java
- src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
- src/test/java/seedu/address/testutil/PersonUtil.java
Fixes #376 
Preposed merge commit message:
>The repeated usage of string literals violates the DRY principle
> (e.g. "add" for the add command word, "p/" for phone prefix).
>
>Let's replace these string literals with the constants defined for
> them (e.g. AddCommand.COMMAND_WORD for "add",
>CliSyntax.PREFIX_PHONE for "p/").
> Remove repeated usage of string literals #376

- src/main/java/seedu/address/commons/util/FxViewUtil.java
- src/main/java/seedu/address/ui/BrowserPanel.java
- src/main/java/seedu/address/ui/CommandBox.java
- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PersonListPanel.java
- src/main/java/seedu/address/ui/ResultDisplay.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/HelpWindow.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/ResultDisplay.fxml
Fixes #309.
```
MainWindow uses AnchorPanes as a placeholder for UiParts. AnchorPane's
default behavior does not make its children fill up the entire space,
thus we have to manually call FxViewUtil#applyAnchorBoundaryParameters()
to do so.
StackPane's default behavior fills up the entire placeholder space
automatically.
Let's
- replace the usage of AnchorPane with StackPane.
- remove FxViewUtil#applyAnchorBoundaryParameters(), since we no
longer have to manually fill up the entire space.
```
> Use StackPanes for holding UiParts #309

- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/commons/core/Version.java
- src/test/java/guitests/guihandles/PersonListPanelHandle.java
- src/test/java/seedu/address/commons/core/ConfigTest.java
Addition to #319 
Enhance #368
> Checkstyle: enforce operators' placement in line wraps #319

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Fixes #311.
```
When accepting a new Person, both UniquePersonList and AddressBook
insert the original object, rather than a copy of the object.
Outside classes are able to indirectly modify the list by using the
same object after inserting them into the list. This is undesirable as
UniquePersonList and AddressBook cannot guarantee that the constraints,
such as the uniqueness of the list, continue to hold, which results in
incorrect behavior for both classes.
Let's ensure that UniquePersonList and AddressBook are actually storing
copies of the Person object, rather than the original object, so that
outside classes are not able to modify them after it is inserted into
the list or book.
```
> AddressBook#addPerson() does not copy the Person #311

- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/EditCommandIntegrationTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/testutil/AddressBookBuilder.java
Fixes #456 
```
Update tests to use assertEquals(Model, Model)
Tests check for equality of the individual components of Model 
(AddressBook and FilteredList). The following code snippet shows an 
example:
assertEquals(expectedAddressBook, model.getAddressBook());
assertEquals(expectedFilteredList, model.getFilteredPersonList());
This can be simplified by checking for equality of the entire Model
directly using ModelManager#equals().
Let's implement Model#equals() and update the tests to check for
equality of Model using assertEquals(expectedModel, model).
```
> Update tests to compare at Model level #456

- src/main/java/seedu/address/commons/core/index/Index.java
- src/main/java/seedu/address/commons/events/ui/JumpToListRequestEvent.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/SelectCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/SelectCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/commons/core/index/IndexTest.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Fixes #438
```
The usages of zero-based indices and one-based indices are mixed
throughout the codebase. Both uses int, and are only differentiated by
different suffixes for the variable names (e.g int zeroBasedIndex,
int oneBasedIndex).
The index base can be easily confused and is prone to error. The
conversion also takes place at different areas of the codebase and is
not consistent.
Let's create an Index class that understands how to convert to a
both zero-based and one-based index, and update the codebase to use
Index instead of int when handling user inputs.
Index from the point when a new user input is being parsed, so that if
the current component wants to communicate with another component, it
can send an Index to avoid having to know what base the …
```
> Create a new Index class #438

- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Part of #401 
```
ParserUtil#split() has no unit test.
It exhibits undesirable behaviours such as not properly splitting the
string when there are leading and trailing white spaces. For example, 
the string " abc def" will be split into: an empty string and "abc def",
instead of two strings "abc" and "def". It also allows the method to be
called when there are fewer than 2 parts.
Let's fix those issues and create unit tests for the method.
```
> Create unit tests for ParserUtil#splitPreamble() #401 

- .gitignore
- build.gradle
- docs/UsingGradle.adoc
- src/main/java/seedu/address/ui/HelpWindow.java
Fixes #417.
Also fixes #419.
```
The help window accesses the online version of the documentation.
Users are unable to access it if they are offline. Furthermore, the
application version for the online documentation may not match the
application version that the user is using.
Let's change the help window to use an offline version instead, and
deploy the offline version to the 'src/main/resources/' folder such 
that shadowJar will automatically bundle the documentation with the app.
```
> Make help documentation accessible offline #417

- src/test/java/guitests/AddressBookGuiTest.java
- src/test/java/guitests/ErrorDialogGuiTest.java
- src/test/java/guitests/guihandles/MainGuiHandle.java
- src/test/java/guitests/guihandles/MainWindowHandle.java
Part of #459.
```
MainGuiHandle recreates a new Handle whenever one is requested. It also
handles AlertDialog box, even though it is only responsible for the
MainWindow.
There is no need to recreate the handles. Furthermore, MainGuiHandle
should be the owner of all the handles to the components in MainWindow,
but not for any error dialog boxes.
Let's encapsulate the handles in MainGuiHandle. Let's also remove 
getAlertDialog(String), and make the callers create the handle on their
own instead.
```
> Clean up MainGuiHandle #459

- src/main/java/seedu/address/ui/BrowserPanel.java
- src/main/java/seedu/address/ui/CommandBox.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PersonListPanel.java
- src/main/java/seedu/address/ui/ResultDisplay.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/resources/view/BrowserPanel.fxml
- src/main/resources/view/CommandBox.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/ResultDisplay.fxml
Fixes #448. Also fixes #517.
```
The components accept a placeholder in their parameter in order for them
to add themselves into the placeholder. Therefore the placeholder acts
like a parent to the component.
The components themselves should not know about their parent placeholder
as this creates a bi-directional dependency coupling.
Let's remove the placeholder parameter in all component's constructor, and
let MainWindow add the component to the placeholder instead.
The components no longer fills up the entire space of the placeholder as
it now contains the root node of the component as well. Let's also
modify the .fxml to allow the component to fill up the entire space.
```
> ui: Remove bidirectional dependencies in UiParts #448

- src/test/java/guitests/ErrorDialogGuiTest.java
- src/test/java/guitests/GuiRobot.java
- src/test/java/guitests/guihandles/CommandBoxHandle.java
- src/test/java/guitests/guihandles/GuiHandle.java
- src/test/java/guitests/guihandles/HelpWindowHandle.java
- src/test/java/guitests/guihandles/MainMenuHandle.java
- src/test/java/guitests/guihandles/PersonListPanelHandle.java
Fixes #502.
Fixes #139.
```
The current uses of `guiRobot.sleep()` in our gui tests can be
categorized into two groups:
(A) To prevent the tests from executing too fast, as that prevents us
from visually examining the progression of the test.
(B) To wait for something to happen on the JavaFX Application thread.
Both types of uses of `guiRobot.sleep()` are undesirable. Group (A)
unfairly makes our GUI tests slower in headless mode, as in headless
mode we can't visually examine GUI test progression anyway. Group (B)
is wrong and can lead to flaky tests, as sleeping for a set amount of
time does not guarantee that what we are waiting for actually occurs on
the JavaFX Application thread.
Let's
- Add GuiRobot#pauseForHuman() (for group A) for pauses that are …
```
> Revamp sleep() for Gui tests #502

- src/test/java/seedu/address/logic/commands/ExitCommandTest.java
- src/test/java/seedu/address/logic/commands/HelpCommandTest.java
- src/test/java/seedu/address/logic/commands/SelectCommandTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
- src/test/java/seedu/address/testutil/EventsCollector.java
Fixes #504.
```
Some command tests check that the correct events are being triggered by
manually subscribing to the events that they are expecting.
We already have EventsCollector class in our codebase that catches all
possible events, and allows us to extract data from the triggered
events as well.
Let's replace all manual subscription of events with EventsCollector
instead.
```
> Use EventsCollector when testing commands #504

- src/test/java/guitests/AddCommandTest.java
- src/test/java/guitests/AddressBookGuiTest.java
- src/test/java/guitests/EditCommandTest.java
- src/test/java/guitests/ErrorDialogGuiTest.java
Part of #459.
```
Let's clean up AddressBookGuiTest by:
- Removing the while loop that waits for the stage to show in the 
setup() phase. FxToolkit#showStage() automatically blocks until
the stage shows, so the wait is unnecessary.
- Creating the guiRobot only in AddressBookGuiTest. It need not be
recreated and can be shared by everyone.
- Reducing the visibility of assertMatching(...) and raise(...) from 
public to private.
- Renaming method parameters that does not conform to coding standards.
- Renaming setupSpec() to setupOnce().
- Changing cleanup()'s throws declaration from TimeoutException to 
Exception.
- Renaming assertMatching(...) to assertCardMatchesPerson(...).
```
> Clean up AddressbookGuiTest #459

- src/main/java/seedu/address/ui/UiManager.java
- src/test/java/guitests/ErrorDialogGuiTest.java
- src/test/java/guitests/guihandles/AlertDialogHandle.java
Part of #459.
```
Let's
- Extract out commonly used strings and objects as constants to avoid
violating DRY principle.
- Remove unnecessary declaration of runtime exception 
InterruptedException.
- Create methods in AlertDialogHandle, allowing us to verify the contents
of the error dialog box.
- Inline AlertDialogHandle#isMatching(String, String), as it should be
the responsibility of ErrorDialogGuiTest to verify the content.
```
> Clean up ErrorDialogGuiTest #459

- src/main/java/seedu/address/ui/BrowserPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PersonListPanel.java
- src/main/java/seedu/address/ui/UiManager.java
Fixes #498 
```
UiManager is catching events such as JumpToListRequestEvent which then 
calls methods to cause the PersonListPanel to scroll to the 
corresponding location.
There is no need for a high-level component such as UiManager to catch 
these events. As such, the individual components that are handling 
these events ought to catch them instead.
Let's shift the catching of events into the classes that are handling 
them.
```
> Shift event handling methods out of UiManager #498

- src/test/java/seedu/address/logic/LogicManagerTest.java
Part of #327 
```
LogicManagerTest contains unit tests for XCommand and XCommandParser.
LogicManagerTest should only be testing the code flow in LogicManager.
Unit tests for XCommand and XCommandParser should instead be written
in XCommandTest and XCommandParserTest respectively.
As these unit tests for XCommand and XCommandParser have been written
already, let's delete the tests that are not relevant to 
LogicManagerTest.
```
> Clean LogicManagerTest #327

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/ListElementPointer.java
- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/ui/CommandBox.java
- src/main/resources/view/CommandBox.fxml
- src/test/java/guitests/CommandBoxTest.java
- src/test/java/seedu/address/logic/ListElementPointerTest.java
```
The user is only able to see their previously typed commands through
the history command.
The user may need to access their previously typed commands quickly in
order to fix a previous typo, or to reuse the input for another
variation.
Let's add a function that allows users to retrieve the previous and
next input in the history by pressing the up and down arrow keys
respectively.
```
> Allow up and down buttons to get previous and next input respectively

- docs/DeveloperGuide.adoc
When doing a new release, MainApp#VERSION needs to be updated to match
the release version number.
This step is not reflected in DeveloperGuide.adoc's release devops
procedure.
Let's add the step for updating the version number in MainApp.
> DeveloperGuide.adoc: Add step for updating version number in MainApp

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/tag/UniqueTagList.java
- src/test/java/seedu/address/model/AddressBookTest.java
Fixes #539
```
UniqueTagList has 2 overloaded methods to set tags:
setTags(UniqueTagList) and setTags(Collection).
Person#setTags(Set) constructs a UniqueTagList from the set of tags
passed in. It then calls UniqueTagList#setTags(UniqueTagList),
which then calls setAll(UniqueTagList#internalList).
This makes the construction of UniqueTagList unnecessary as no
other properties of UniqueTagList are required here.
Also, AddressBook#resetData(ReadOnlyAddressBook) calls 
setTags(Collection), followed by a catch clause asserting that 
AddressBooks should not have duplicate tags.
This makes the code unnecessarily long as there is a try-catch
block, where the catch block does not do anything significant.
Let’s replace these methods with UniqueTagList#setTags(Set<Tag>).
Person#setTags(Set<Tag>) …
```
> Clean up UniqueTagList #539

- build.gradle
- src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionChangedEvent.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/ReadOnlyPerson.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/main/java/seedu/address/ui/BrowserPanel.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/java/seedu/address/ui/PersonListPanel.java
- src/test/java/guitests/AddCommandTest.java
- src/test/java/guitests/AddressBookGuiTest.java
- src/test/java/guitests/EditCommandTest.java
- src/test/java/guitests/SelectCommandTest.java
- src/test/java/guitests/guihandles/PersonListPanelHandle.java
- src/test/java/seedu/address/ui/PersonCardTest.java
Fixes #292. Note that tags are still not completely binded and we still have to manually initialize it, though it now updates automatically whenever there are changes made to the tags.
```
ReadOnlyPerson is not observable. Whenever a ReadOnlyPerson is added 
or updated, PersonListPanel creates a new PersonCard and initialises 
it with the ReadOnlyPerson's details.
This is inefficient as multiple cards have to be deleted and
re-created whenever a ReadOnlyPerson is updated. Also, there is an
additional call to set the ReadOnlyPerson in the list of PersonCards
to update the view i.e updating the ReadOnlyPerson does not 
automatically update the view.
Let's update ReadOnlyPerson to be observable and teach PersonCard
to bind its view to the ReadOnlyPerson objects so that whenever they
are …
```
> Make ReadOnlyPerson observable #292

- src/test/java/guitests/guihandles/CommandBoxHandle.java
- src/test/java/guitests/guihandles/MainMenuHandle.java
- src/test/java/seedu/address/ui/CommandBoxTest.java
Part of #459.
```
guiRobot#type(...) and guiRobot#push(...) internally pauses after
pressing the given keys.
We do not need to call guiRobot#pauseForHuman() ourselves after calling
these two key pressing methods.
Let's remove the redundant guiRobot#pauseForHuman() calls.
```
> Remove unnecessary pauses after pressing keys with GuiRobot #459

- src/test/java/guitests/AddCommandTest.java
- src/test/java/guitests/AddressBookGuiTest.java
- src/test/java/guitests/ClearCommandTest.java
- src/test/java/guitests/DeleteCommandTest.java
- src/test/java/guitests/EditCommandTest.java
- src/test/java/guitests/FindCommandTest.java
- src/test/java/guitests/SelectCommandTest.java
- src/test/java/guitests/StatusBarFooterTest.java
- src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/ClearCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
- src/test/java/seedu/address/logic/commands/SelectCommandTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
- src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
- src/test/java/seedu/address/testutil/AddressBookBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- src/test/java/seedu/address/ui/BrowserPanelTest.java
- src/test/java/seedu/address/ui/PersonCardTest.java
- src/test/java/seedu/address/ui/PersonListPanelTest.java
Fixes #569 
```
TypicalPersons is a utility class that creates preset Persons for tests
to use. Some methods and fields are non-static.
This makes it troublesome for test classes to access these preset
Persons as they have to create a TypicalPersons object prior to
accessing the Person objects.
Let's make all methods and fields in TypicalPersons to be static.
```
> TypicalPersons: Make all methods and fields static #569

- .gitignore
When running the application/tests in IntelliJ, a new 'out/' directory
will be created.
The 'out/' directory contains build files. They should not be included
in the repository.
Let's update .gitignore to ignore the 'out/' build directory.
> gitignore: Ignore 'out/' build directory

- src/test/java/guitests/DeleteCommandTest.java
- src/test/java/guitests/SelectCommandTest.java
- src/test/java/guitests/guihandles/PersonListPanelHandle.java
- src/test/java/seedu/address/ui/PersonListPanelTest.java
- src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Fixes #563 
```
PersonListPanelHandle is a test helper class that encapsulates
PersonListPanel. It has methods that return PersonCard.
Tests should not directly interact with Node objects such as PersonCard
as it breaks the encapsulation of the PersonCard object.
Let's teach existing methods in PersonListPanelHandle to return 
PersonCardHandle instead of PersonCard. 
```
> PersonListPanelHandle: No longer returns PersonCard #563

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
Fixes #621 
```
UniquePersonList: Simplify logic of updatePerson(...)
This method retrieves the person in the list to be updated, and calls
Person#resetData(ReadOnlyPerson) to update the values of that person.
We do not need to retrieve the person in the list to be updated, to
update the list accordingly.
Let’s simplify the logic by setting the updated Person object in place
of the person to be updated.
```
> Simplify UniquePersonList logic #621

- src/main/java/seedu/address/commons/core/EventsCenter.java
Fixes #598 
Cleaning up this issue so that I can skip adding header comment for this trivial method.
> EventsCenter: remove registerHandler method return type #598

- src/test/java/guitests/guihandles/BrowserPanelHandle.java
- src/test/java/guitests/guihandles/WebViewUtil.java
- src/test/java/seedu/address/TestApp.java
- src/test/java/seedu/address/ui/BrowserPanelTest.java
- src/test/java/systemtests/AddressBookSystemTest.java
- src/test/java/systemtests/DeleteCommandSystemTest.java
Fixes #644, also fixes #642 
```
There are some areas of code in system tests that have minor bugs and
code issues. For e.g. AddressBookSystemTest's header comments is
outdated and TestApp#getModel() is returning the wrong model.
Let's fix these minor issues.
```
> Tidy up System Tests #644

- src/test/java/systemtests/DeleteCommandSystemTest.java
Fixes #641
```
DeleteCommandSystemTest is missing test cases pertaining to 
filtered lists.
```
> DeleteCommandSystemTest: Add missing test case #641

- docs/DeveloperGuide.adoc
Fixes #461 
```
There are no quotes in the Developer Guide, but there are quote marks
in it.
This is misleading.
Let's remove these quote marks.
```
> Developer Guide: Fix unintended quote marks #461

- docs/DeveloperGuide.adoc
Fixes #608 
```
There are formatting errors in the use cases. For example, some use
cases are not properly indented.
Let's fix them.
```
> Developer Guide: Fix formatting errors in the use case #608

- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/AddressBookSystemTest.java
- src/test/java/systemtests/ClearCommandSystemTest.java
- src/test/java/systemtests/DeleteCommandSystemTest.java
- src/test/java/systemtests/EditCommandSystemTest.java
- src/test/java/systemtests/FindCommandSystemTest.java
- src/test/java/systemtests/SelectCommandSystemTest.java
```
DeleteCommandSystemTest can be cleaner. For example, the header 
comments can be updated to be written in point forms, and the test 
cases can be segmented into different categories.
This causes it to be harder for future developer to understand the 
code.
Let's clean up DeleteCommandSystemTest.
```
> Cleanup DeleteCommandSystemTest

- src/test/java/systemtests/EditCommandSystemTest.java
```
We use assert to show that a precondition is met before executing a
test.
Asserts should not be used in test cases as they can be disabled.
Let’s replace assert statements with junit.Assert
```
> EditCommandSystemTest: Replace assert with junit.Assert

- src/test/java/systemtests/DeleteCommandSystemTest.java
```
We use Assume to show that a precondition is met before executing a
test.
Assume should not be used in test cases as the Travis build passes even
if tests are ignored. This forces developers to have to manually
verify each Travis build to ensure that no tests are ignored.
Let’s replace Assume with Assert.
```
> DeleteCommandSystemTest: Replace Assume with Assert

- src/test/java/seedu/address/ui/GuiUnitTest.java
Fixes #675
```
EventsCenter is a Singleton object, which is a possible cause of state
leaks between tests as the state of the static objects are preserved
across tests.
EventsCenter isn’t cleared after each GuiUnitTest is executed, as such
it stores a reference to its subscribers, which causes these objects
to not be removed by Garbage Collection after the test is done
executing. These extra objects can possibly cause future tests to fail.
Currently, AddCommandTest fails when run locally on IntelliJ together
with other tests.
Let’s update GuiUnitTest to clears subscribers from EventsCenter after
each test.
Credits of debugging this issue goes to @pyokagan.
```
> GuiUnitTest: Clears subscribers from EventsCenter after each test #675

- .travis.yml
- build.gradle
Fixes #358 
4.0.7-alpha has been released. Besides being the latest and greatest
version, 4.0.7-alpha also contains a proper working headless mode for
Linux.
Without this upgrade, attempting to run `./gradlew headless guiTests` on
Linux would result with the GUI tests failing with the following
exception:
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalAccessException: Class org.testfx.toolkit.impl.ApplicationLauncherImpl can not access a member of class com.sun.glass.ui.monocle.HeadlessPlatform with modifiers ""
Caused by:
java.lang.RuntimeException: java.lang.IllegalAccessException: Class org.testfx.toolkit.impl.ApplicationLauncherImpl can not access a member of class com.sun.glass.ui.monocle.HeadlessPlatform with modifiers ""
Caused by: …
> Fix errors in GUI tests when upgrading to the new version (4.0.6-alpha) of TestFx #358

- src/test/java/systemtests/SelectCommandSystemTest.java
```
SelectCommandSystemTest can be cleaner. For example, the header 
comments can be updated to be written in point forms, and the test 
cases can be segmented into different categories.
This causes it to be harder for future developer to understand the 
code.
Let's clean up SelectCommandSystemTest.
```
> Clean up SelectCommandSystemTest

- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/AddressBookSystemTest.java
- src/test/java/systemtests/FindCommandSystemTest.java
- src/test/java/systemtests/SelectCommandSystemTest.java
```
AddCommandSystemTest can be cleaner. For example, the header 
comments can be updated to be written in point forms, and the test 
cases can be segmented into different categories.
This causes it to be harder for future developer to understand the 
code.
Let's clean up AddCommandSystemTest.
```
> Clean up AddCommandSystemTest

- config/travis/check-eof-newline.sh
```
check-eof-newline.sh doesn't properly handle filenames with spaces,
instead treating them as multiple files instead.
For example, we can create a file whose name has spaces, e.g.
'filename with spaces.txt'. Ensure that the file has some content inside
so that Git will detect it as a text file so it will be checked by
check-eof-newline.sh:
echo 'content' >'filename with spaces.txt'
Then use git-add to track the file:
git add 'filename with spaces.txt'
Then run check-eof-newline.sh:
./config/travis/check-eof-newline.sh
check-eof-newline.sh will then spew out the following errors:
tail: cannot open './filename' for reading: No such file or directory
tail: cannot open './with' for reading: No such file or directory
tail: cannot open './spaces.txt' for reading: No such file or directory …
```
> check-eof-newline: handle filenames with spaces

- src/main/java/seedu/address/logic/ListElementPointer.java
- src/test/java/seedu/address/logic/ListElementPointerTest.java
```
The constructor’s header comments state that this object is backed by
a defensive copy of the list that is passed in as parameter. However,
the code does not reflect this behaviour.
The constructor should use create a defensive copy of the list to
prevent unintentional modifications to the backing list whenever the
list passed in as parameter is modified.
Let’s update ListElementPointer(List<String>) to create a defensive copy
of the list.
```
> ListElementPointer(List<String>): Update code to tally with comments

- docs/DeveloperGuide.adoc
```
The glossary uses literal blocks for formatting definitions, which looks
strange because literal blocks are usually used for preformatted text
such as source code.
Instead, let's use a labeled list, which has a formatting that is more
in line with a glossary definition list.
Convert the paragraph anchors into inline anchors[1], so that the items
are joined into one single labeled list with two items, rather than
being chopped into two separate labeled lists with one item each.
[1] See http://asciidoctor.org/docs/user-manual/#anchordef for the
difference between a paragraph anchor and an inline anchor.
```
---
> DeveloperGuide: use labeled list for glossary

- README.adoc
- docs/AboutUs.adoc
- docs/DeveloperGuide.adoc
- docs/LearningOutcomes.adoc
- docs/UsingTravis.adoc
- docs/team/johndoe.adoc
```
Many of our adoc files have the following boilerplate:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
This boilerplate used to be required in order for inter-document cross
references to work when viewing the adoc files directly on GitHub. This
was because GitHub errnously set the outfilesuffix as `.html` instead of
`.adoc`, which resulted in broken links.
However, as the asciidoctor user guide[1] states:
This configuration is no longer necessary on GitHub since GitHub now
sets the value of outfilesuffix to match the file extension of the
source file. However, it’s still required in GitHub-like
environments such as GitLab.
Indeed, this seems to be the case on GitHub. As our project is unlikely
to be hosted on other "GitHub-like environments such as GitLab" in the
near future, …
```
> docs: remove env-github outfilesuffix boilerplate

- build.gradle
Fixes #752 
```
Simplify the build.gradle file by removing unnecessary/unused stuff, and
standardizing the code style.
```
> Simplify build.gradle file

- build.gradle
- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
```
Switch to `full` xrefstyle so that cross references will display the
section/figure numbers as well, allowing readers to easily find the
referenced section/figure by their number.
Switch to using asciidoctor's auto figure numbering which is less error
prone and doesn't require us to pollute the commit diff when figure
numbers need to be updated.
```
> docs: use full xrefstyle and figure auto-numbering

- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Fixes #738 
Hi everyone! I'm Vivek here and I decided to work on this issue as a first-time contributor.
There is no check to ensure that the preamble for AddCommand is empty or not. 
Let's add a check to ensure that it is not empty and update the AddCommandParserTest.
> AddCommandParser accepts invalid command format #738

- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Phone.java
- src/main/java/seedu/address/model/tag/Tag.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/XmlAdaptedPerson.java
- src/main/java/seedu/address/storage/XmlAdaptedTag.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/person/AddressTest.java
- src/test/java/seedu/address/model/person/EmailTest.java
- src/test/java/seedu/address/model/person/NameTest.java
- src/test/java/seedu/address/model/person/PhoneTest.java
- src/test/java/seedu/address/model/tag/TagTest.java
- src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/Assert.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
```
The model classes Name, Email, Address, Phone and Tag perform input validation
and string trimming even though that is not the responsibility of the model
layer.
Fix this by moving the input validation and string trimming logic from these
classes to the parser/storage layer where they should rightfully be.
```
> Improve separation of concerns between parser/storage layer and model layer

- build.gradle
```
The allTests, nonGuiTests, guiTests tasks are implemented as separate
tasks which are unaware of whether each other is being run. This leads
to strange behavior such as the following command which runs some tests
multiple times:
./gradlew allTests nonGuiTests guiTests
These tasks are also not integrated with the `test` task, which is
provided by default by the `java` plugin. This is the de facto task for
running tests, and is run by default by other commonly-used tasks such
as `./gradlew check` and `./gradlew build`.
Fix this by making all of these tasks aware of each other. The `test`
task is configured to be *the* task that runs the tests, while the
nonGuiTests and guiTests tasks are converted to dummy tasks which just
serve to inform the `test` task of whether to run the GUI tests …
```
> build.gradle: teach test tasks to work together

- docs/AboutUs.adoc
- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/johndoe.adoc
Fixes #771 
Proposed commit message
```
Restructure sample Project Portfolio Page
The structure of the sample Project Portfolio Page (PPP) makes it
difficult to read due to,
1. mixing of UG/DG extracts inside the main document body.
2. mismatch of PPP heading levels and those of UG/DG extracts
Let's restructure it to clearly separate,
1. summary of Contributions in point form
2. contributions to the UG
3. contributions to the DG
Also, let's tweak heading levels of PPP so that headings of included
extracts match the the heading structure of PPP.
To match the restructured sample PPP, let's tweak existing docs
as follows:
1. Add 'proposed' features to the DG and UG so that they can be
included in the sample PPP.
2. Remove horizontal lines in the DG segments included in PPP
so that they don't …
```
> Restructure sample Project Portfolio Page for easier reading #771

- docs/DeveloperGuide.adoc
Fixes #682.
```
There's `3.1.1. Design Considerations`, but there aren’t any further
numberings such as 3.1.2.
Let’s update the header `Undo/Redo mechanism` to be simply `Undo/Redo`,
and let’s segment this section to have 2 sub-headers `Mechanism` and
`Design Considerations`.
```
> DeveloperGuide: Update Undo/Redo numbering

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/storage/XmlFileStorage.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Fixes #264 
Hi, I'm Jun An here. Working on this issue as my first contribution 
to this project
In some places of the code we use `assert false` to indicate the
execution has reached an unacceptable state.
This is not compliant with our code style (as revised by [1])  which
states `throw new AssertionError()` is preferred for such situations.
Let's replace `assert false` with `throw new AssertionError()` where
applicable.
[1] oss-generic/process#19
> Replace use of `assert false` with `throw new AssertionError()` #264

- src/main/java/seedu/address/logic/commands/EditCommand.java
```
getTags() returns the same set of tags stored by this object, while
setTags(Set<Tag>) assigns the given Set<Tag> to its field without
defensive copy.
Callers can modify the state of the Set<Tag> externally, thus breaking
EditPersonDescriptor’s encapsulation.
Let's update getTags() to return an unmodifiable set, and 
setTags(Set<Tag>) to perform a defensive copy of the input before 
assigning it to its field.
```
> EditPersonDescriptor: update methods to perform defensive copy

- src/main/java/seedu/address/ui/UiManager.java
Fixes #734 
```
UiManager calls primaryStage.setTitle(). This is called by MainWindow as
well.
The setting of the title should not be the job of UiManager as different
Windows may have different titles; each Window should be responsible for
assigning its own title.
Let's remove the duplicate code in UiManager.
```
> UiManager: delete duplicate code  #734

- src/main/java/seedu/address/logic/LogicManager.java
Fixes #729 
Proposed commit message:
```
The LogicManager constructor initialises several fields using 
the 'this' keyword.
Using 'this' keyword for some fields is unnecessary as these 
fields are not shadowed by a method or constructor parameter.
Let's remove unnecessary 'this' keywords from LogicManager
constructor to reduce noise and conform to coding standards.
```
> LogicManager: constructor does not follow coding standard's usage of 'this' #729

- docs/DeveloperGuide.adoc
Fixes #800 
Proposed Commit Message: 
```
The hyperlink in Developer Guide is broken due to incorrect file extension.
Let's update the hyperlink's file extension to .adoc in order to fix it.
```
>  DeveloperGuide.adoc: fix broken hyperlink to coding standard #800

- config/checkstyle/checkstyle.xml
Fixes #370 
On a side note, in `checkstyle.xml` there is a property called `optional` under the module`SuppresionFilter`which has a default value. 
```
<module name="SuppressionFilter">
<property name="file" value="config/checkstyle/suppressions.xml"/>
<property name="optional" value="false"/>
</module>
```
However, according to the [Checkstyle documentation](http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter), this property is included even though it is a default value. Do we remove it or keep it as it is?
> Checkstyle: remove unnecessary properties with default values #370

- src/main/java/seedu/address/storage/XmlAdaptedPerson.java
- src/main/java/seedu/address/storage/XmlAdaptedTag.java
- src/main/java/seedu/address/storage/XmlAddressBookStorage.java
- src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
- src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
- src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
- src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
- src/test/data/XmlSerializableAddressBookTest/invalidTagAddressBook.xml
- src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
- src/test/java/seedu/address/commons/util/XmlUtilTest.java
- src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
- src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
Fixes #749, and partly fixes #725
```
XmlSerializableAddressBook does not have a method to convert itself to
an AddressBook object. It implements ReadOnlyAddressBook and has
getPersonList() and getTagList() methods, which the caller uses to
create an AddressBook object.
By implementing ReadOnlyAddressBook, the overridden getPersonList()
and getTagList() methods are unable to throw IllegalValueException to
higher level components for error handling if there's errors in the
.xml save file.
Let's implement a toModelType() method in XmlSerializableAddressBook
to allow the XmlSerializableAddressBook to convert itself to an 
AddressBook and remove it's implementation of ReadOnlyAddressBook.
Let's also override the equals(Object) method in XmlAdaptedPerson,
XmlAdaptedTag and …
```
> Storage layer needs proper error handling #749

- src/main/java/seedu/address/model/person/Email.java
- src/test/java/seedu/address/model/person/EmailTest.java
Fixes #743 
Do note that the domain name has to be 2 characters long so that it does not start and end with dots or hyphens.
On a side note, the updated email regex just allows the use of more characters to solve the issue. Should a more restrictive validation be used instead?
For instance this regex,
```
^[\\w!#$%&’*+/=?`{|}~^-]+(?:\\.[\\w!#$%&’*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$
```
sets a predefined length for the top-level domain name (which would be **edu** in someone@u.nus.edu) and restricts trailing and consecutive dots.
> Email regex validation does not accept `+` #743

- .travis.yml
- build.gradle
- docs/DummySearchPage.html
- src/main/java/seedu/address/ui/BrowserPanel.java
- src/test/java/seedu/address/ui/BrowserPanelTest.java
- src/test/java/systemtests/AddressBookSystemTest.java
Fixes #733 
```
BrowserPanel loads the Google search page whenever a person card
is selected. The tests written for this feature verifies that the
loaded web page is indeed the Google search page with the person's
name.
When many forks of this project are running automated tests, too many
search requests are sent to Google, causing us to exceed the search
service’s rate limits. This is an abuse of Google’s search service.
Also, this causes our tests to fail as the loaded web page will be
redirected to a captcha page.
Let’s update BrowserPanel to load DummySearchPage.html which is hosted
on GitHub Pages. GitHub Pages serve static web pages which requires
much less processing power, thus it is more unlikely for us to exceed
the search service’s rate limits.
```
> BrowserPanel: load dummy page #733

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/UndoableCommand.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
- src/test/java/seedu/address/logic/commands/RedoCommandTest.java
- src/test/java/seedu/address/logic/commands/SelectCommandTest.java
- src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
Fixes #737 
EditCommand and DeleteCommand stores the target index of the person to edit
or delete respectively.
As a result, redoing of these index-based commands will be executed on the incorrect
person due to different indexing in differing views.
Let's update EditCommand and DeleteCommand to find and store the personToEdit
or personToDelete respectively before it's first execution. This ensures that future
execution of the same command will be on the correct person.
> Issue with undo/redo and modifications to filtered lists #737

- src/main/java/seedu/address/ui/HelpWindow.java
- src/test/java/systemtests/HelpCommandSystemTest.java
Fixes #727 
On a side note, should this TODO be converted into a separate issue or is it already covered by #551?
```
/**
* TODO: This test is incomplete as it is missing test cases.
*/
public class HelpCommandSystemTest extends AddressBookSystemTest {
```
> HelpWindow: May interfere with UI Components while active #727

- src/main/java/seedu/address/storage/XmlAdaptedPerson.java
- src/test/data/XmlUtilTest/invalidPersonField.xml
- src/test/data/XmlUtilTest/missingPersonField.xml
- src/test/data/XmlUtilTest/validPerson.xml
- src/test/java/seedu/address/commons/util/XmlUtilTest.java
- src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/Assert.java
Fixes #725
```
XmlAdaptedPerson#toModelType() does not have a non-null check for each
parameter in person before the isValid*(String).
When null value is passed into the parameter's isValid*(String) check,
a NullPointerException is thrown, causing the app to crash.
Let's update XmlAdaptedPerson#toModelType() to have a separate non-null
check for each parameter before passing them into the isValid*(String)
check.
```
> XmlAdaptedPerson#toModelType(): Enforce checking of required parameters #725

- src/main/resources/view/MainWindow.fxml
- src/test/java/seedu/address/ui/MainWindowCloseTest.java
Fixes #826 
```
The MainWindow does not have an event handler to handle external
requests (such as the close button or through the taskbar) to close
the MainWindow.
This may cause the app to not close properly since MainApp#stop() is
not called as the ExitAppRequestEvent is not raised. MainApp#stop() is
the method used to call Platform#exit() and System#exit(int) which
closes our app and all remaining open windows. Thus, if MainApp#stop()
is not called, the app may continue to run even after the MainWindow is
closed, causing existing HelpWindows to remain open even when the user
expects the app to stop.
According to the life-cycle section in the documentation on JavaFX
Application[1], the app will only finish and call MainApp#stop() when
the app either calls Platform#exit() or when the …
```
> HelpWindow: help window stays open even after exiting by clicking the close button #826

- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
fixes #830 
```
AddressBook#removePerson(Person) returns true if the person passed into
this method can be found in the internal list. 
UniquePersonList#remove(Person) returns true if the person passed into
this method can be found in the internal list, and false otherwise.
They both also throw PersonNotFoundException if a person cannot be
found.
Returning a boolean is not required as the thrown exception would
indicate that the person cannot be found.
Let's update the return type for AddressBook#removePerson(Person) and 
UniquePersonList#remove(Person) to void.
```
> UniquePersonList, AddressBook: update return type for remove and removePerson #830

- .travis.yml
- appveyor.yml
- build.gradle
- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Fixes #374, part of #681 and #706.
```
build.gradle: upgrade to use Java 9
The project currently runs on Java 8.
We should ensure compatibility with the latest public version as soon
as it is out.
Let's upgrade the project to run on Java 9.
```
> build.gradle: update to build project using Java 9 #374

- README.adoc
- build.gradle
- src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionChangedEvent.java
- src/main/java/seedu/address/ui/BrowserPanel.java
- src/main/java/seedu/address/ui/PersonListPanel.java
- src/test/java/guitests/guihandles/PersonCardHandle.java
- src/test/java/guitests/guihandles/PersonListPanelHandle.java
- src/test/java/seedu/address/ui/BrowserPanelTest.java
- src/test/java/seedu/address/ui/PersonListPanelTest.java
- src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
- src/test/java/systemtests/AddressBookSystemTest.java
Fixes #796.
```
personListView is of type ListView<PersonCard>. We use EasyBind library
to map the Person objects to PersonCard objects. The mapping / applying
of Function<? super F, ? extends E> occurs only when either get(int) or
getRemoved() methods are called[1]; the creation of PersonCard objects
occur only when either of these methods are called.
The ClearCommand deletes all Person objects. When we have large number
of persons and getRemoved() is called, all the corresponding cards
will be created prior to them being removed. As creation of PersonCard
objects are costly, the app slows down tremendously.
Let's revert ListView<PersonCard> to ListView<Person>.
PersonListViewCell will create the PersonCard object. According to
javadoc for Cell that "it is not feasible to create an …
```
> PersonListPanel#personListView: revert type change #796

- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/guitests/GuiRobot.java
- src/test/java/guitests/guihandles/StageHandle.java
- src/test/java/seedu/address/ui/HelpWindowTest.java
- src/test/java/systemtests/HelpCommandSystemTest.java
Fixes #819.
```
MainWindow creates a new HelpWindow instance and shows it whenever
MainWindow#handleHelp() is called.
This allows multiple help windows to be opened at the same time by
executing HelpCommand, pressing Help menu button or F1 multiple times.
Multiple help windows should be disallowed since each help window
are exactly the same thus having extra copies is unnecessary.
Let's update MainWindow to hold and show a single HelpWindow instance.
```
> HelpWindow: multiple help windows can be opened #819

- build.gradle
fixes #707 (eventually, right now it just starts to fix it)
This is a start towards upgrading towards JUnit5. It does not changes any tests, but it makes it such that Gradle is able to read JUnit5 tests and execute them.
One thing to keep in consideration if we want to change the tests to be JUnit5 tests:
Right now there is no easy way to do the temporary folder rule, it might be messy to create our own version.
> JUnit: Update to use latest version #707

- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
resolves #685 
```
If no tag is set when constructing a new Person using PersonBuilder, 
the tag "friends" is added to the Person by default.
This should not happen as tags are optional. As a result, all Persons 
in TypicalPersons have the "friends" tag while this isn't the case for 
the Persons in typicalPersonsAddressBook.xml, which is unintuitive.
Let's replace the default tag in PersonBuilder with an empty set of 
tags.
```
> TypicalPersons: Unintuitive interaction with PersonBuilder #685

- src/test/java/seedu/address/ui/PersonListPanelTest.java
```
LIST_CREATION_TIMEOUT has a value of 5500ms, which causes
PersonListPanelTest#performanceTest() to fail if the list creation takes
longer than the set amount of time.
This value is too small and this test executed on Travis CI sometimes
fails. [1]
Let's increase the value of LIST_CREATION_TIMEOUT by 4000ms so that
this test becomes very unlikely to fail.
[1]: https://travis-ci.org/se-edu/addressbook-level4/builds/358246241
```
> PersonListPanelTest: fix flaky test

- src/main/java/seedu/address/commons/util/CollectionUtil.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
- src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
- src/test/java/guitests/guihandles/PersonCardHandle.java
- src/test/java/seedu/address/commons/util/CollectionUtilTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- src/test/java/seedu/address/ui/PersonListPanelTest.java
- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/EditCommandSystemTest.java
Fixes #742 
Some changes to note:
In `AddCommandSystemTest`, line 120 was changed from `assertCommandSuccess(CARL)` to `assertCommandSuccess(AMY)`  to test for duplicate persons in the next few lines as the duplicate person tests require the default person to be used, which is either AMY or BOB.
While porting from [se-edu/addressbook-level2#122](https://github.com/se-edu/addressbook-level2/issues/122), I realized only name and phone were checked. Since email is a unique identifier for a person as well, I added that to the equality method.
> Add different levels of comparison to equality methods of Person class #742

- build.gradle
- src/test/java/guitests/GuiRobot.java
- src/test/java/seedu/address/ui/HelpWindowTest.java
```
HelpWindowTest#focus_helpWindowNotFocused_focused() test checks that
the HelpWindow#focus() method will cause the HelpWindow to be in focus
when called. The test first asserts that the HelpWindow is not in focus
first after it is shown, being calling this method and asserting that
the HelpWindow is now in focus.
When tests are run in non-headless mode, the HelpWindow will be in
focus immediately after it is shown, thus our first assertion is
incorrect, causing the test to consistently fail in non-headless mode.
Let's add a method GuiRobot#removeFocus(), and update the test to call
this method to remove focus from the HelpWindow after it is shown
to ensure the first assertion is correct in non-headless mode.
```
> HelpWindowTest: fix failing test in non-headless mode

- .gitattributes
> .gitattributes: treat all *.pdf files as binary

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/SelectCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/storage/XmlFileStorage.java
- src/test/java/seedu/address/TestApp.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
- src/test/java/seedu/address/testutil/AddressBookBuilder.java
- src/test/java/seedu/address/testutil/Assert.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/AddressBookSystemTest.java
- src/test/java/systemtests/DeleteCommandSystemTest.java
- src/test/java/systemtests/EditCommandSystemTest.java
- src/test/java/systemtests/SystemTestSetupHelper.java
```
Some parsers in the `parsers` package throw ParseException on a parse
error, others throw IllegalValueException.
Given that they are *all* parsers, let's make them all throw
ParseException for consistency.
```
> parsers: throw ParseException consistently

- src/test/java/seedu/address/logic/commands/ClearCommandTest.java
```
Tests in ClearCommandTest always pass because the actual and expected
model refer to the same instance;
`assertEquals(expectedModel, actualModel)` is always true.
As a result, the model's state isn't correctly verified.
Let's update these tests to correctly verify the model's state.
```
> ClearCommandTest: fix tautological tests

- src/main/java/seedu/address/logic/CommandHistory.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/Command.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/HelpCommand.java
- src/main/java/seedu/address/logic/commands/HistoryCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/RedoCommand.java
- src/main/java/seedu/address/logic/commands/SelectCommand.java
- src/main/java/seedu/address/logic/commands/UndoCommand.java
- src/test/java/seedu/address/logic/CommandHistoryTest.java
- src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/ClearCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/ExitCommandTest.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/commands/HelpCommandTest.java
- src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
- src/test/java/seedu/address/logic/commands/RedoCommandTest.java
- src/test/java/seedu/address/logic/commands/SelectCommandTest.java
- src/test/java/seedu/address/logic/commands/UndoCommandTest.java
```
Ensure that all command tests verify their model state and command
history.
Our commands forgot that their bound model and commandHistory are part
of their state, and did not check them in their `#equals(...)`
implementations. Combine Command#setData(...) and Command#execute()
together to fix this, and allow us to streamline our command testing
code by removing all of the `prepareCommand(...)` helper methods.
```
> Combine Command#setData(...) and Command#execute() together

- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Email.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Phone.java
- src/main/java/seedu/address/model/tag/Tag.java
- src/main/java/seedu/address/storage/XmlAdaptedPerson.java
- src/main/java/seedu/address/storage/XmlAdaptedTag.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/EditCommandSystemTest.java
Fixes #399 
```
Each of these classes: Name, Phone, Email, Address and Tag has a 
MESSAGE_X_CONSTRAINTS and X_VALIDATION_REGEX (X referring to the name of 
the class).
It is unnecessary to have X as part of the names of these constants. For 
example, Name.MESSAGE_NAME_CONSTRAINTS doesn't seem to provide more 
information than Name.MESSAGE_CONSTRAINTS.
As such, let's remove X as part of the names of these constants.
```
> Shorten names of constants of Person's attributes #399

- src/test/java/seedu/address/ui/PersonListPanelTest.java
```
createXmlFileWithPersons() saves the location of the temporarily
generated .xml file to:
src/test/data/sandboxmanyPersons.xml
instead of:
src/test/data/sandbox/manyPersons.xml
It is likely that the original author of the test intended the saving
location to be the latter, given that it has always resolved to the
latter until we revamped the path handling logic in AddressBook to use
java.nio.file.Path API, which introduced this discrepancy (commit
9eac635d9da1a71c81587ba66cab1911977a863b).
Saving the temporary .xml file to the 'sandbox' folder is also ideal as
the folder is git-ignored, so even if JVM crashes and does not clean
up the temporary file, students would not accidentally commit this
potentially _enormous_ .xml file into the repository.
Let's fix the incorrect path.
```
> PersonListPanelTest#createXmlFileWithPersons(): Fix incorrect path

- build.gradle
The current version of TestFX dependency we are using is 4.0.12-alpha.
TestFX version 4.0.15-alpha has been announced for a while and it gives
better support for JDK11[1], which we may wish to upgrade to in the
future.
To keep us updated with TestFX's development, let's upgrade TestFX
dependency to its latest stable version 4.0.15-alpha.
[1] https://github.com/TestFX/TestFX/issues/640#issuecomment-436079910
> build.gradle: upgrade TestFX dependency to 4.0.15-alpha

- config/checkstyle/checkstyle.xml
- config/checkstyle/suppressions.xml
We are currently using the DTD files from `http://checkstyle.sourceforge.net/`
and `http://puppycrawl.com/` in our config file of checkstyle.
However, due to security reason, checkstyle decided to remove DTDs from
above websites and ask users to use the DTD files from
`https://checkstyle.org/`[1].
Let's update the addresses of DTD files correspondingly.
Meanwhile, update the version of suppression DTD file to 1.2 because it is
the version suggested from checkstyle. [2]
[1] https://github.com/checkstyle/checkstyle/issues/6478
[2] https://checkstyle.org/config_filters.html#SuppressionFilter_Examples
> Edit the addresses of DTD files used for checkstyle

- src/test/java/seedu/address/commons/util/StringUtilTest.java
Currently, StringUtilTest has a method named
isUnsignedPositiveInteger. However, the method tested is actually
named isNonZeroUnsignedInteger. This can cause confusion in the
naming.
It appears that the tested method was renamed to
isNonZeroUnsignedInteger in #460, however the test was not renamed
then.
To maintain consistent naming convention, lets rename the test method
to isNonZeroUnsignedInteger too.
> StringUtilTest: Rename test method name

- src/test/java/seedu/address/commons/core/ConfigTest.java
ConfigTest contains an unused ExpectedException. It appears that the
ExpectedException was first introduced in [1].
However, since its introduction, there have been no tests within
ConfigTest that potentially throws an expected exception.
Hence, to make our code tidier and to remove unnecessary code, let's
remove the ExpectedException together with their imports.
[1] https://github.com/se-edu/addressbook-level4/commit/75942c90c04ff0469d5bb26873b85cd094f37797
> ConfigTest: Remove unused ExpectedException

- src/test/java/seedu/address/commons/util/StringUtilTest.java
Currently, in StringUtilTest#getDetails_exceptionGiven, we use
Hamcrest's string matching and assert libraries.
This library was introduced in [1], however no documentation was
logged on why we specifically used these Hamcrest libraries. In fact,
this is the only instance in the entire project where we use this
dependency.
We are only using the contains API of the Hamcrest library, whose
corresponding functionality is already implemented in Java standard
String library. Hence, the Hamcrest library serves little extra
benefit, and introuduces extra dependencies for our tests.
Hence, let's remove the Hamcrest libraries and replace them with the
equivalent Java and JUnit APIs.
[1] https://github.com/se-edu/addressbook-level4/commit/75942c90c04ff0469d5bb26873b85cd094f37797
> StringUtilTest: Remove Hamcrest String matcher

- src/test/java/seedu/address/ui/UiPartTest.java
The tests in UiPartTest do not use the ExpectedException.
Let's remove it.
P. S. Somehow didn't notice this until now...
> UiPartTest: remove unused ExpectedException

- src/test/java/seedu/address/commons/core/VersionTest.java
- src/test/java/seedu/address/model/VersionedAddressBookTest.java
VersionTest and VersionedAddressBookTest contain tests that align
multi-line parameter lists instead of using 8-spaces to indent the
lines.
Let's bring them in line with our coding style and use 8-spaces.
> VersionTest, VersionedAddressBookTest: Use 8-spaces indent for parameter lists

- src/test/java/seedu/address/TestApp.java
- src/test/java/systemtests/AddressBookSystemTest.java
- src/test/java/systemtests/SystemTestSetupHelper.java
Constants SAVE_LOCATION_FOR_TESTING and DEFAULT_PREF_LOCATION_FOR_TESTING exist within TestApp. This reduces our flexibility for testing as test drivers like AddressBookSystemTest cannot configure the values. This design also violates the tell-don't-ask principle as AddressBookSystemTest has to retrieve the constant value from within TestApp, then initialise TestApp with these default values.
TestApp also has an unused default constructor. Additionally, we can also set its initialDataSupplier variable to private and remove the its redundant default null supplier.
To improve the code quality within our code base, let's clean up TestApp.
> TestApp: code quality cleanups

- src/test/java/seedu/address/commons/core/VersionTest.java
- src/test/java/seedu/address/commons/core/index/IndexTest.java
- src/test/java/seedu/address/commons/util/AppUtilTest.java
- src/test/java/seedu/address/commons/util/CollectionUtilTest.java
- src/test/java/seedu/address/commons/util/ConfigUtilTest.java
- src/test/java/seedu/address/commons/util/FileUtilTest.java
- src/test/java/seedu/address/commons/util/StringUtilTest.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/model/UserPrefsTest.java
- src/test/java/seedu/address/model/VersionedAddressBookTest.java
- src/test/java/seedu/address/model/person/AddressTest.java
- src/test/java/seedu/address/model/person/EmailTest.java
- src/test/java/seedu/address/model/person/NameTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/model/person/PhoneTest.java
- src/test/java/seedu/address/model/person/UniquePersonListTest.java
- src/test/java/seedu/address/model/tag/TagTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
- src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
- src/test/java/seedu/address/ui/UiPartTest.java
We have many different ways of checking for thrown exceptions. These are not standardized, and make it difficult for a reader because they have to learn the different ways of throwing exceptions.
Let's standardize the way we test error handling behavior, specifically towards using Assert#assertThrows.
> Tests: standardize the way we check for thrown exceptions

- build.gradle
We include the TestFX-JUnit dependency in our build.gradle since [1].
However, we also implement our own StageRule and SystemTestSetupHelper
to setup the UI environment for unit tests and system tests
respectively. These classes replicate TestFX-JUnit's ApplicationTest
behavior [2], so our tests do not need to extend from ApplicationTest.
According to TestFX's documentation [3], TestFX-JUnit provides the
ApplicationTest class that we can inherit from. Since we already
implement the necessary setup routine, we do not need to inherit from
ApplicationTest. TestFX-JUnit thus adds no value to our project now.
Let's remove the TestFX-JUnit dependency.
[1]: https://github.com/se-edu/addressbook-level4/commit/7916322fad9d11ef3fa7ca67574062bb6de3e950
[2]: …
> build.gradle: Remove TestFX-JUnit dependency

- .travis.yml
- README.adoc
- appveyor.yml
- build.gradle
- config/checkstyle/checkstyle.xml
- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- gradle.properties
- src/main/java/seedu/address/Main.java
- src/main/java/seedu/address/MainApp.java
- src/test/java/seedu/address/ui/GuiUnitTest.java
- src/test/java/systemtests/AddressBookSystemTest.java
> Migrate to JDK 11+

- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/main/java/seedu/address/logic/parser/SelectCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/ui/ListElementPointer.java
Fixes #357. 
There are some typos in our codebase related to the usage of `an`.
Let's fix the improper usage of `an` to solve the problem.
> Fix improper usage of `an`

- .gitignore
Fixes #926.
We ignore config.json and preferences.json by adding entries in
.gitignore.
The entries added are too general so git will also ignore other files
with same name, which is an unwanted behavior.
Let's specific the entries in .gitignore to solve the problem.
> .gitignore: standardize and specify entries

- .travis.yml
All builds with references to Oracle JDK11 breaks as Oracle appears
to be restricting headless downloads. Travis is also moving to remove
support for Oracle JDKs from install-jdk.sh
No work is required by students as their local builds on Oracle JDK
should behave similarly to OpenJDK.
> Change travis build to use OpenJDK instead of Oracle

- src/main/java/seedu/address/ui/CommandBox.java
Fixes #635.
Update handleCommandEntered() to return once an empty string is encountered.
> CommandBox: update handleCommandEntered() for empty strings

- config/checkstyle/checkstyle.xml
- src/test/java/seedu/address/commons/util/StringUtilTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/person/UniquePersonListTest.java
- src/test/java/seedu/address/testutil/PersonUtil.java
Fixes #1024 
```
checkstyle.xml: enforce line wrap indentation of 8 spaces
The OSS Java Coding standard states that indentation for wrapped
lines should be 8 spaces. This however, is not enforced in the 
AddressBook4's checkstyle. 
Let's follow the OSS Java Coding standard and enforce line
wrap indentation of 8 spaces, for consistencies' sake.
```
> [#1024] checkstyle.xml: enforce line wrap indentation of 8 spaces
